/**
 * Kernel scan tests (Ω-SCAN)
 */

import { test } from 'node:test';
import assert from 'node:assert';
import { readFileSync } from 'fs';
import { join } from 'path';
import { scanArtifact } from '../src/kernel/scan';
import { ViolationCode } from '../src/kernel/types';

function loadDocFixture(name: string): string {
  const path = join(__dirname, '..', '..', 'fixtures', 'docs', name);
  return readFileSync(path, 'utf-8');
}

test('sample_policy.md should pass scan (clean policy)', () => {
  const text = loadDocFixture('sample_policy.md');
  const result = scanArtifact(text, 'policy');

  assert.strictEqual(result.clean, true, 'Policy should be clean');
  assert.strictEqual(result.violations.length, 0, 'Should have no violations');
});

test('sample_agent_prompt.txt should fail with multiple violations', () => {
  const text = loadDocFixture('sample_agent_prompt.txt');
  const result = scanArtifact(text, 'prompt');

  assert.strictEqual(result.clean, false, 'Prompt should have violations');
  assert.ok(result.violations.length > 0, 'Should have violations');

  // Should detect implicit authority
  const implicitAuthViolations = result.violations.filter(
    (v) => v.code === ViolationCode.OMEGA_IMPLICIT_AUTHORITY_IN_TEXT
  );
  assert.ok(implicitAuthViolations.length > 0, 'Should detect implicit authority claims');

  // Should detect irreversible actions without signoff
  const irreversibleViolations = result.violations.filter(
    (v) => v.code === ViolationCode.OMEGA_IRREVERSIBLE_WITHOUT_SIGNOFF
  );
  assert.ok(
    irreversibleViolations.length > 0,
    'Should detect irreversible actions without signoff'
  );
});

test('text with "AI decides" should fail', () => {
  const text = 'The AI decides which action to take based on the situation.';
  const result = scanArtifact(text, 'policy');

  assert.strictEqual(result.clean, false);
  const violations = result.violations.filter(
    (v) => v.code === ViolationCode.OMEGA_IMPLICIT_AUTHORITY_IN_TEXT
  );
  assert.ok(violations.length > 0, 'Should detect "AI decides" pattern');
});

test('text with "model approves" should fail', () => {
  const text = 'The model approves requests automatically when criteria are met.';
  const result = scanArtifact(text, 'policy');

  assert.strictEqual(result.clean, false);
  const violations = result.violations.filter(
    (v) => v.code === ViolationCode.OMEGA_IMPLICIT_AUTHORITY_IN_TEXT
  );
  assert.ok(violations.length > 0, 'Should detect "model approves" pattern');
});

test('text with delete without human signoff should warn', () => {
  const text = 'The system will delete old records automatically.';
  const result = scanArtifact(text, 'policy');

  assert.strictEqual(result.clean, false);
  const violations = result.violations.filter(
    (v) => v.code === ViolationCode.OMEGA_IRREVERSIBLE_WITHOUT_SIGNOFF
  );
  assert.ok(violations.length > 0, 'Should detect delete without signoff');
});

test('text with delete AND human approval should pass', () => {
  const text =
    'The system will delete old records only after receiving human approval from an administrator.';
  const result = scanArtifact(text, 'policy');

  // Should not flag this as irreversible without signoff
  const violations = result.violations.filter(
    (v) => v.code === ViolationCode.OMEGA_IRREVERSIBLE_WITHOUT_SIGNOFF
  );
  assert.strictEqual(violations.length, 0, 'Should not flag when human approval is mentioned');
});

test('clean informational text should pass', () => {
  const text = `
    This document describes the architecture of the system.
    Users can view reports and summaries generated by the analytics module.
    All data is read from the database in read-only mode.
  `;
  const result = scanArtifact(text, 'doc');

  assert.strictEqual(result.clean, true, 'Clean informational text should pass');
  assert.strictEqual(result.violations.length, 0);
});

test('text with self-approve should fail', () => {
  const text = 'Agents can self-approve minor changes to improve efficiency.';
  const result = scanArtifact(text, 'policy');

  assert.strictEqual(result.clean, false);
  const violations = result.violations.filter(
    (v) => v.code === ViolationCode.OMEGA_IMPLICIT_AUTHORITY_IN_TEXT
  );
  assert.ok(violations.length > 0, 'Should detect "self-approve" pattern');
});
